FROM node:23.7.0-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose the port your app listens on
EXPOSE 8080

# Use the development command defined in package.json
CMD ["npm", "run", "start:dev"]
